apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: employee-app
  namespace: micro
  labels:
    team: micro
spec:
  selector:
    matchLabels:
      app: employee
  endpoints:
  - port: web
    path: /prometheusMetrics
